const centreOfExcellence = [
  "Surgical Oncology",
  "Medical Oncology",
  "Radiation Oncology",
  "Hemato-Oncology and BMT",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Critical Care",
  "Dental Services",
  "Dermatology",
  "ENT",
  "Emergency Medicine",
  "Gastroenterology",
  "General Medicine",
  "General Surgery including Laparoscopy",
  "Gynaecology",
  "Nephrology including Dialysis",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Orthopaedics",
  "Psychiatry",
  "Pulmonology",
  "Urology",
  "Vascular Surgery",
  "Breast Clinic",
  "Lipedema Clinic",
  "Spine Clinic",
  "Covid Center",
  "Plastic Surgery",
  "Surgical Gastroenterology",
  "Obesity Clinic",
];

const ourServices = [
  "Doctor Consultation",
  "Video Consultation",
  "Health Checkups",
  "Radiology Imaging",
  "Pharmacy",
];

const cancerTypes = [
  "Breast Cancer",
  "Brain Cancer",
  "Cervix Cancer",
  "Ovarian Cancer",
  "Anal Cancer",
  "Liver Cancer",
  "Colon Cancer",
  "Endometrial Cancer",
  "Pancreatic Cancer",
  "Stomach Cancer",
  "Skin Cancer",
  "Prostate Cancer",
  "Thyroid Cancer",
  "Testicular Cancer",
  "Lung Cancer",
  "Brain Tumour",
  "Oesophageal Cancer",
  "Oral Cancer",
];

export { cancerTypes, centreOfExcellence, ourServices };
